# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

jobs:
  - job: Job1
    timeoutInMinutes: 0
    pool:
      name: XamVMSSDec011

    steps:
    - task: CmdLine@1
      inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net5.0\'
        arguments: 'sftabview-xamarin AutomationDev sftabview-xamarin-tests With10Scripts TabViewSamples TabviewScripts'
    

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'D:\AutomationReports\'
  
  - job: Job2
    timeoutInMinutes: 0
    pool:
      name: XamVMSSDec011

    steps:
    - task: CmdLine@1
      inputs:
        filename: 'UIAutomationConsole.exe'
        workingFolder: '$(Build.SourcesDirectory)\net5.0\'
        arguments: 'sfrating-xamarin AutomationDev sfrating-xamarin-tests With10Automation SfRatingSample SfRatingScripts'
    

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'D:\AutomationReports\'